//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FARMACIA_SEMI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FAR_UNIDAD_MED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAR_UNIDAD_MED()
        {
            this.FAR_ARTICULO = new HashSet<FAR_ARTICULO>();
        }
        
        [Display(Name = "CODIGO MEDIDA")]
        public decimal ID_MEDIDA { get; set; }
        [Display(Name = "MEDIDA")]
        [Required(ErrorMessage = "{0} CAMPO REQUERIDO")]
        public string DESC_MEDIDA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAR_ARTICULO> FAR_ARTICULO { get; set; }
    }
}
