//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FARMACIA_SEMI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FAR_VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAR_VENTA()
        {
            this.FAR_DETALLE_VENTA = new HashSet<FAR_DETALLE_VENTA>();
        }
    
        public string FACTURA { get; set; }
        [Display(Name = "SUCURSAL")]
        public Nullable<decimal> ID_SUCURSAL { get; set; }
        [Display(Name = "ESTATUS")]
        public Nullable<decimal> ID_ESTATUS { get; set; }
        [Display(Name = "CLIENTE")]
        public string NIT { get; set; }
        [Display(Name = "PAGO")]
        public Nullable<decimal> ID_TPAGO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual FAR_CLIENTE FAR_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAR_DETALLE_VENTA> FAR_DETALLE_VENTA { get; set; }
        public virtual FAR_ESTATUS FAR_ESTATUS { get; set; }
        public virtual FAR_SUCURSAL FAR_SUCURSAL { get; set; }
        public virtual FAR_TIPO_PAGO FAR_TIPO_PAGO { get; set; }
    }
}
